#!/bin/sh

#Pre-requisites for my unix environment
sudo apt-get update
sudo apt-get -y install git zsh tmux vim-gnome exuberant-ctags silversearcher-ag

#Tools to customize shell and editor
curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#Custom settings
curl https://raw.githubusercontent.com/MamesPalmero/dotfiles/master/vimrc -o ~/.vimrc
curl https://raw.githubusercontent.com/MamesPalmero/dotfiles/master/tmux.conf -o ~/.tmux.conf

#Install vim plugins
vim -c ":PlugInstall" -c ":qa"

#Default shell zsh
chsh -s /bin/zsh

zsh
