# -----Env variables-----

export ZSH="$HOME/.oh-my-zsh"

if which nvim > /dev/null; then
  export EDITOR="nvim"
  export VISUAL="nvim"
else
  export EDITOR="vim"
  export VISUAL="vim"
fi

[[ $TMUX = "" ]] && export TERM="xterm-256color"



# -----Oh my zsh-----

# https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

plugins=(
  zsh-autosuggestions
  colored-man-pages
)

# Load Oh-My-Zsh
source $ZSH/oh-my-zsh.sh



# -----Shell options-----

unsetopt auto_cd # Disable auto_cd to avoid collisions between executables and folders called same

# aliases
alias gst="git status"
alias gch="git checkout"
alias gd="git diff"
alias gf="git fetch --all"

# fzf
source ~/.fzf.zsh

# asdf-vm
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash


# -----Other options-----
export ERL_AFLAGS="-kernel shell_history enabled"
